name: p2pdmmariabeatrizcoelho
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.3
    provider: ^4.0.4
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true

assets:
- images/1.png
- images/5.png
- images/6.png
- images/7.png
- images/bee.gif
- images/fasedois.gif
- images/procrastina.gif
- images/Presente mãe.png
- images/English power point 1.png

fonts:
- family: Schyler
- asset: fonts/Schyler-Regular.ttf
- asset: fonts/Schyler-Italic.ttf
- style: italic
- family: Trajan Pro
- asset: fonts/TrajanPro.ttf
- asset: fonts/TrajanPro_Bold.ttf 
- weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages